# Generated by Django 6.1.1 on 2026-09-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=64, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64)),
                ('razorpay_signature', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.internprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='company.internshiptrack')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
