# Generated by Django 6.1.1 on 2026-09-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(help_text='Path (relative to MEDIA_ROOT/templates/<kind>/) where index.html and img/ live.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(blank=True, help_text='Leave blank to use this as the site-wide default template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.internshiptrack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(help_text='Path (relative to MEDIA_ROOT/templates/<kind>/) where index.html and img/ live.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(blank=True, help_text='Leave blank to use this as the site-wide default template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='company.internshiptrack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
