# Generated by Django 6.1.1 on 2026-09-03 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('college_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number (7–15 digits, optional +country code).', regex='^\\+?\\d{7,15}$')])),
                ('has_paid', models.BooleanField(default=False)),
                ('certificate_id', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
