# Generated by Django 6.1.1 on 2026-09-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='intern_id',
            field=models.CharField(blank=True, help_text='Unique Intern ID format: RBS/INT/XXXXXX', max_length=30, null=True, unique=True),
        ),
    ]
