# Generated by Django 6.1.1 on 2026-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodule',
            options={'ordering': ['track', 'module_number', 'order', 'id']},
        ),
        migrations.AddField(
            model_name='taskmodule',
            name='body_points',
            field=models.JSONField(blank=True, default=list, help_text="List of bullet points for 'What You'll Do'"),
        ),
        migrations.AddField(
            model_name='taskmodule',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of deliverable field labels expected from interns'),
        ),
        migrations.AddField(
            model_name='taskmodule',
            name='duration_info',
            field=models.CharField(blank=True, default='Day 1 – Day 5 · High priority', max_length=160),
        ),
        migrations.AddField(
            model_name='taskmodule',
            name='module_number',
            field=models.PositiveIntegerField(default=1, help_text='Module sequence number, e.g. 1 for Module 1'),
        ),
        migrations.AddField(
            model_name='usertaskprogress',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict, help_text='Submitted deliverable links/text from intern'),
        ),
        migrations.AlterField(
            model_name='taskmodule',
            name='description',
            field=models.TextField(blank=True, help_text='General summary or notes'),
        ),
    ]
