# Generated by Django 6.1.1 on 2026-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_taskmodule_options_taskmodule_body_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiptrack',
            name='points',
            field=models.TextField(blank=True, default='', help_text='Comma-separated points/skills (e.g. Prompt Engineering & APIs, RAG & Vector Databases)'),
        ),
        migrations.AddField(
            model_name='internshiptrack',
            name='track_image',
            field=models.ImageField(blank=True, help_text='Optional icon or image for this track', null=True, upload_to='track_images/'),
        ),
    ]
