# Generated by Django 6.1.1 on 2026-10-09 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_internshiptrack_points_internshiptrack_track_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Track Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='internshiptrack',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for this internship track', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='company.trackcategory'),
        ),
    ]
