# Generated by Django 6.1.1 on 2026-10-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_trackcategory_internshiptrack_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiptrack',
            name='source_link',
            field=models.CharField(blank=True, default='', help_text='Optional Google Drive link or resource URL for track materials', max_length=500),
        ),
        migrations.AddField(
            model_name='taskmodule',
            name='source_link',
            field=models.CharField(blank=True, default='', help_text='Optional Google Drive link or resource URL for module files and learning materials', max_length=500),
        ),
    ]
